# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    ur_arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

ur_arm_group_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    command_publish_rate: 50
    allow_partial_joints_goal: false
    hardware_state_has_offset: true
    deduce_states_from_derivatives: true
    # constraints:
    #   goal_time: 0.6
    #   stopped_velocity_tolerance: 0.05
    # stop_trajectory_duration: 0.5